/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Bookings: () => import('#controllers/bookings_controller'),
  Customers: () => import('#controllers/customers_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Documents: () => import('#controllers/documents_controller'),
  Enquiries: () => import('#controllers/enquiries_controller'),
  Home: () => import('#controllers/home_controller'),
  Invoices: () => import('#controllers/invoices_controller'),
  Payments: () => import('#controllers/payments_controller'),
  PortalBookingTypes: () => import('#controllers/portal_booking_types_controller'),
  PortalBookings: () => import('#controllers/portal_bookings_controller'),
  PortalDashboard: () => import('#controllers/portal_dashboard_controller'),
  PortalEnquiries: () => import('#controllers/portal_enquiries_controller'),
  PortalInvoices: () => import('#controllers/portal_invoices_controller'),
  PortalQuotations: () => import('#controllers/portal_quotations_controller'),
  PortalRecoveryReports: () => import('#controllers/portal_recovery_reports_controller'),
  PortalRegistration: () => import('#controllers/portal_registration_controller'),
  PortalSession: () => import('#controllers/portal_session_controller'),
  PortalUsers: () => import('#controllers/portal_users_controller'),
  Profile: () => import('#controllers/profile_controller'),
  QuickbooksSettings: () => import('#controllers/quickbooks_settings_controller'),
  Quotations: () => import('#controllers/quotations_controller'),
  Receipts: () => import('#controllers/receipts_controller'),
  RecoveryReports: () => import('#controllers/recovery_reports_controller'),
  Reports: () => import('#controllers/reports_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Session: () => import('#controllers/session_controller'),
  Suppliers: () => import('#controllers/suppliers_controller'),
  SystemSettings: () => import('#controllers/system_settings_controller'),
  Users: () => import('#controllers/users_controller'),
  WorkflowCycles: () => import('#controllers/workflow_cycles_controller'),
}
