/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'entityId', 'entityType', 'id', 'ipAddress', 'metadata', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: number | null
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: string | null
  @column()
  declare userId: number | null
}

export class BookingSchema extends BaseModel {
  static $columns = ['amountPaidByDz', 'approvedBy', 'assignedUserId', 'branchId', 'confirmedAt', 'costCenter', 'createdAt', 'currency', 'customerId', 'dateRequested', 'departDate', 'destination', 'dzPaymentDate', 'dzPaymentReference', 'dzPaymentStatus', 'enquiryData', 'generalLedgerAccount', 'id', 'invoiceReceiptNumber', 'itineraryService', 'notes', 'pax', 'pnr', 'portalBookingTypeId', 'productType', 'reference', 'returnDate', 'status', 'supplierId', 'totalAmount', 'travelerName', 'tripName', 'tripReason', 'updatedAt'] as const
  $columns = BookingSchema.$columns
  @column()
  declare amountPaidByDz: string
  @column()
  declare approvedBy: string | null
  @column()
  declare assignedUserId: number | null
  @column()
  declare branchId: number
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column()
  declare costCenter: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare customerId: number
  @column.date()
  declare dateRequested: DateTime | null
  @column.date()
  declare departDate: DateTime
  @column()
  declare destination: string
  @column.date()
  declare dzPaymentDate: DateTime | null
  @column()
  declare dzPaymentReference: string | null
  @column()
  declare dzPaymentStatus: string
  @column()
  declare enquiryData: string | null
  @column()
  declare generalLedgerAccount: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceReceiptNumber: string | null
  @column()
  declare itineraryService: string | null
  @column()
  declare notes: string | null
  @column()
  declare pax: number
  @column()
  declare pnr: string | null
  @column()
  declare portalBookingTypeId: number | null
  @column()
  declare productType: string | null
  @column()
  declare reference: string
  @column.date()
  declare returnDate: DateTime | null
  @column()
  declare status: string
  @column()
  declare supplierId: number | null
  @column()
  declare totalAmount: string
  @column()
  declare travelerName: string | null
  @column()
  declare tripName: string | null
  @column()
  declare tripReason: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookingItemSchema extends BaseModel {
  static $columns = ['bookingId', 'createdAt', 'description', 'id', 'lineTotal', 'quantity', 'supplierId', 'unitPrice', 'updatedAt'] as const
  $columns = BookingItemSchema.$columns
  @column()
  declare bookingId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lineTotal: string
  @column()
  declare quantity: number
  @column()
  declare supplierId: number | null
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BranchSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = BranchSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClientAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'email', 'fullName', 'id', 'isActive', 'lastLoginAt', 'password', 'privileges', 'role', 'updatedAt'] as const
  $columns = ClientAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare privileges: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['branchId', 'company', 'createdAt', 'email', 'fullName', 'id', 'notes', 'phone', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare branchId: number | null
  @column()
  declare company: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DocumentSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'documentType', 'filePath', 'fileSize', 'id', 'mimeType', 'referenceId', 'referenceType', 'status', 'title', 'updatedAt', 'uploadedById'] as const
  $columns = DocumentSchema.$columns
  @column()
  declare branchId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentType: string
  @column()
  declare filePath: string
  @column()
  declare fileSize: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string | null
  @column()
  declare referenceId: number | null
  @column()
  declare referenceType: string | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uploadedById: number | null
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['amountPaid', 'bookingId', 'branchId', 'createdAt', 'currency', 'customerId', 'documentId', 'dueDate', 'id', 'invoiceNumber', 'issueDate', 'notes', 'quickbooksInvoiceId', 'quickbooksSyncStatus', 'recoveryReportItemId', 'status', 'subtotal', 'taxAmount', 'totalAmount', 'updatedAt'] as const
  $columns = InvoiceSchema.$columns
  @column()
  declare amountPaid: string
  @column()
  declare bookingId: number | null
  @column()
  declare branchId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare customerId: number
  @column()
  declare documentId: number | null
  @column.date()
  declare dueDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceNumber: string
  @column.date()
  declare issueDate: DateTime
  @column()
  declare notes: string | null
  @column()
  declare quickbooksInvoiceId: string | null
  @column()
  declare quickbooksSyncStatus: string | null
  @column()
  declare recoveryReportItemId: number | null
  @column()
  declare status: string
  @column()
  declare subtotal: string
  @column()
  declare taxAmount: string
  @column()
  declare totalAmount: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'entityId', 'entityType', 'id', 'readAt', 'title', 'type', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: number | null
  @column()
  declare entityType: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column()
  declare userId: number
}

export class PaymentRecordSchema extends BaseModel {
  static $columns = ['amount', 'branchId', 'createdAt', 'currency', 'customerId', 'documentId', 'id', 'invoiceId', 'notes', 'paymentDate', 'paymentMethod', 'paymentReference', 'receiptId', 'recordedById', 'reference', 'status', 'updatedAt'] as const
  $columns = PaymentRecordSchema.$columns
  @column()
  declare amount: string
  @column()
  declare branchId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare customerId: number
  @column()
  declare documentId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number | null
  @column()
  declare notes: string | null
  @column.date()
  declare paymentDate: DateTime
  @column()
  declare paymentMethod: string
  @column()
  declare paymentReference: string | null
  @column()
  declare receiptId: number | null
  @column()
  declare recordedById: number | null
  @column()
  declare reference: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PortalBookingFieldSchema extends BaseModel {
  static $columns = ['createdAt', 'fieldKey', 'fieldType', 'id', 'label', 'mapsTo', 'options', 'placeholder', 'portalBookingTypeId', 'required', 'sortOrder', 'updatedAt'] as const
  $columns = PortalBookingFieldSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fieldKey: string
  @column()
  declare fieldType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare mapsTo: string
  @column()
  declare options: string | null
  @column()
  declare placeholder: string | null
  @column()
  declare portalBookingTypeId: number
  @column()
  declare required: boolean
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PortalBookingTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'iconKey', 'id', 'isActive', 'name', 'slug', 'sortOrder', 'tabLabel', 'updatedAt'] as const
  $columns = PortalBookingTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare iconKey: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column()
  declare tabLabel: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PortalRegistrationRequestSchema extends BaseModel {
  static $columns = ['company', 'createdAt', 'email', 'fullName', 'id', 'message', 'phone', 'status', 'updatedAt'] as const
  $columns = PortalRegistrationRequestSchema.$columns
  @column()
  declare company: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column()
  declare phone: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuickbooksAppSettingSchema extends BaseModel {
  static $columns = ['clientId', 'clientSecretEncrypted', 'createdAt', 'environment', 'id', 'redirectUri', 'scopes', 'updatedAt', 'updatedByUserId'] as const
  $columns = QuickbooksAppSettingSchema.$columns
  @column()
  declare clientId: string | null
  @column()
  declare clientSecretEncrypted: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare environment: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare redirectUri: string | null
  @column()
  declare scopes: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedByUserId: number | null
}

export class QuickbooksConnectionSchema extends BaseModel {
  static $columns = ['accessTokenEncrypted', 'accessTokenExpiresAt', 'companyName', 'connectedByUserId', 'createdAt', 'defaultIncomeAccountId', 'defaultServiceItemId', 'defaultServiceItemName', 'environment', 'id', 'realmId', 'refreshTokenEncrypted', 'syncEnabled', 'updatedAt'] as const
  $columns = QuickbooksConnectionSchema.$columns
  @column()
  declare accessTokenEncrypted: string
  @column.dateTime()
  declare accessTokenExpiresAt: DateTime
  @column()
  declare companyName: string | null
  @column()
  declare connectedByUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultIncomeAccountId: string | null
  @column()
  declare defaultServiceItemId: string | null
  @column()
  declare defaultServiceItemName: string | null
  @column()
  declare environment: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare realmId: string
  @column()
  declare refreshTokenEncrypted: string
  @column()
  declare syncEnabled: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuickbooksSyncRecordSchema extends BaseModel {
  static $columns = ['attemptCount', 'createdAt', 'entityType', 'id', 'lastError', 'localId', 'quickbooksId', 'realmId', 'syncStatus', 'syncedAt', 'updatedAt'] as const
  $columns = QuickbooksSyncRecordSchema.$columns
  @column()
  declare attemptCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column()
  declare localId: number
  @column()
  declare quickbooksId: string | null
  @column()
  declare realmId: string
  @column()
  declare syncStatus: string
  @column.dateTime()
  declare syncedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuotationSchema extends BaseModel {
  static $columns = ['approvedAt', 'bookingId', 'branchId', 'createdAt', 'createdById', 'currency', 'customerId', 'documentId', 'id', 'lineItems', 'notes', 'reference', 'status', 'subtotal', 'taxAmount', 'totalAmount', 'updatedAt', 'validUntil'] as const
  $columns = QuotationSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare bookingId: number | null
  @column()
  declare branchId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdById: number | null
  @column()
  declare currency: string
  @column()
  declare customerId: number
  @column()
  declare documentId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lineItems: string | null
  @column()
  declare notes: string | null
  @column()
  declare reference: string
  @column()
  declare status: string
  @column()
  declare subtotal: string
  @column()
  declare taxAmount: string
  @column()
  declare totalAmount: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.date()
  declare validUntil: DateTime | null
}

export class ReceiptSchema extends BaseModel {
  static $columns = ['amount', 'branchId', 'createdAt', 'currency', 'customerId', 'documentId', 'id', 'invoiceId', 'notes', 'paymentMethod', 'paymentReference', 'receiptNumber', 'receivedDate', 'recordedById', 'updatedAt'] as const
  $columns = ReceiptSchema.$columns
  @column()
  declare amount: string
  @column()
  declare branchId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare customerId: number
  @column()
  declare documentId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number
  @column()
  declare notes: string | null
  @column()
  declare paymentMethod: string
  @column()
  declare paymentReference: string | null
  @column()
  declare receiptNumber: string
  @column.date()
  declare receivedDate: DateTime
  @column()
  declare recordedById: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecoveryReportSchema extends BaseModel {
  static $columns = ['approvedAt', 'branchId', 'createdAt', 'createdById', 'currency', 'customerId', 'id', 'recoveredAt', 'reportPeriodEnd', 'reportPeriodStart', 'reportReference', 'reportType', 'sentAt', 'status', 'totalAmount', 'updatedAt'] as const
  $columns = RecoveryReportSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare branchId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdById: number | null
  @column()
  declare currency: string
  @column()
  declare customerId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare recoveredAt: DateTime | null
  @column.date()
  declare reportPeriodEnd: DateTime | null
  @column.date()
  declare reportPeriodStart: DateTime | null
  @column()
  declare reportReference: string
  @column()
  declare reportType: string
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare totalAmount: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecoveryReportAuditLogSchema extends BaseModel {
  static $columns = ['action', 'description', 'id', 'newStatus', 'oldStatus', 'performedAt', 'performedByClientId', 'performedByUserId', 'recoveryReportItemId'] as const
  $columns = RecoveryReportAuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newStatus: string | null
  @column()
  declare oldStatus: string | null
  @column.dateTime()
  declare performedAt: DateTime
  @column()
  declare performedByClientId: number | null
  @column()
  declare performedByUserId: number | null
  @column()
  declare recoveryReportItemId: number
}

export class RecoveryReportItemSchema extends BaseModel {
  static $columns = ['amountPaidByDz', 'approvedBy', 'bookingId', 'branchId', 'clientApprovedAt', 'clientQuery', 'clientReviewedAt', 'costCenter', 'createdAt', 'createdById', 'currency', 'customerId', 'dateRequested', 'dzPaymentDate', 'dzPaymentReference', 'dzPaymentStatus', 'generalLedgerAccount', 'id', 'invoiceReceiptNumber', 'itineraryService', 'pnr', 'price', 'productType', 'recoveredAt', 'recoveryReference', 'recoveryReportId', 'recoveryStatus', 'rejectionReason', 'sentToClientAt', 'supplierId', 'supplierInvoiceDocumentId', 'supplierName', 'travelEnd', 'travelStart', 'travelerName', 'tripName', 'tripReason', 'updatedAt', 'updatedById'] as const
  $columns = RecoveryReportItemSchema.$columns
  @column()
  declare amountPaidByDz: string
  @column()
  declare approvedBy: string | null
  @column()
  declare bookingId: number
  @column()
  declare branchId: number
  @column.dateTime()
  declare clientApprovedAt: DateTime | null
  @column()
  declare clientQuery: string | null
  @column.dateTime()
  declare clientReviewedAt: DateTime | null
  @column()
  declare costCenter: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdById: number | null
  @column()
  declare currency: string
  @column()
  declare customerId: number
  @column.date()
  declare dateRequested: DateTime | null
  @column.date()
  declare dzPaymentDate: DateTime | null
  @column()
  declare dzPaymentReference: string | null
  @column()
  declare dzPaymentStatus: string
  @column()
  declare generalLedgerAccount: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceReceiptNumber: string | null
  @column()
  declare itineraryService: string | null
  @column()
  declare pnr: string | null
  @column()
  declare price: string
  @column()
  declare productType: string
  @column.dateTime()
  declare recoveredAt: DateTime | null
  @column()
  declare recoveryReference: string
  @column()
  declare recoveryReportId: number | null
  @column()
  declare recoveryStatus: string
  @column()
  declare rejectionReason: string | null
  @column.dateTime()
  declare sentToClientAt: DateTime | null
  @column()
  declare supplierId: number | null
  @column()
  declare supplierInvoiceDocumentId: number | null
  @column()
  declare supplierName: string | null
  @column.date()
  declare travelEnd: DateTime | null
  @column.date()
  declare travelStart: DateTime | null
  @column()
  declare travelerName: string
  @column()
  declare tripName: string | null
  @column()
  declare tripReason: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedById: number | null
}

export class ReportRunSchema extends BaseModel {
  static $columns = ['createdAt', 'errorMessage', 'generatedById', 'id', 'outputDocumentId', 'parameters', 'status', 'templateId', 'updatedAt'] as const
  $columns = ReportRunSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column()
  declare generatedById: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare outputDocumentId: number | null
  @column()
  declare parameters: string | null
  @column()
  declare status: string
  @column()
  declare templateId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReportTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'filePath', 'id', 'isActive', 'name', 'slug', 'source', 'updatedAt'] as const
  $columns = ReportTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare filePath: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'permission', 'role', 'updatedAt'] as const
  $columns = RolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare permission: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SmsSettingSchema extends BaseModel {
  static $columns = ['accountSid', 'authTokenEncrypted', 'createdAt', 'enabled', 'fromNumber', 'id', 'provider', 'updatedAt', 'updatedByUserId'] as const
  $columns = SmsSettingSchema.$columns
  @column()
  declare accountSid: string | null
  @column()
  declare authTokenEncrypted: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare fromNumber: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedByUserId: number | null
}

export class SmtpSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'enabled', 'fromAddress', 'fromName', 'host', 'id', 'passwordEncrypted', 'port', 'secure', 'updatedAt', 'updatedByUserId', 'username'] as const
  $columns = SmtpSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare fromAddress: string | null
  @column()
  declare fromName: string | null
  @column()
  declare host: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare passwordEncrypted: string | null
  @column()
  declare port: number
  @column()
  declare secure: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedByUserId: number | null
  @column()
  declare username: string | null
}

export class SupplierSchema extends BaseModel {
  static $columns = ['branchId', 'code', 'contactName', 'createdAt', 'email', 'id', 'isActive', 'name', 'notes', 'phone', 'updatedAt'] as const
  $columns = SupplierSchema.$columns
  @column()
  declare branchId: number | null
  @column()
  declare code: string | null
  @column()
  declare contactName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SystemSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'group', 'id', 'isSecret', 'key', 'updatedAt', 'updatedByUserId', 'value'] as const
  $columns = SystemSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare group: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSecret: boolean
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedByUserId: number | null
  @column()
  declare value: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'email', 'fullName', 'id', 'lastAccessedAt', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare branchId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastAccessedAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WhatsappSettingSchema extends BaseModel {
  static $columns = ['apiKeyEncrypted', 'businessAccountId', 'createdAt', 'enabled', 'fromNumber', 'id', 'phoneNumberId', 'provider', 'updatedAt', 'updatedByUserId'] as const
  $columns = WhatsappSettingSchema.$columns
  @column()
  declare apiKeyEncrypted: string | null
  @column()
  declare businessAccountId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare fromNumber: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phoneNumberId: string | null
  @column()
  declare provider: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedByUserId: number | null
}
