function _ts_decorate(decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for(var i = decorators.length - 1; i >= 0; i--)if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
}
/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */ import { BaseModel, column } from '@adonisjs/lucid/orm';
export class AuditLogSchema extends BaseModel {
    static $columns = [
        'action',
        'createdAt',
        'entityId',
        'entityType',
        'id',
        'ipAddress',
        'metadata',
        'userId'
    ];
    $columns = AuditLogSchema.$columns;
}
_ts_decorate([
    column()
], AuditLogSchema.prototype, "action", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], AuditLogSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], AuditLogSchema.prototype, "entityId", void 0);
_ts_decorate([
    column()
], AuditLogSchema.prototype, "entityType", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], AuditLogSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], AuditLogSchema.prototype, "ipAddress", void 0);
_ts_decorate([
    column()
], AuditLogSchema.prototype, "metadata", void 0);
_ts_decorate([
    column()
], AuditLogSchema.prototype, "userId", void 0);
export class BookingSchema extends BaseModel {
    static $columns = [
        'amountPaidByDz',
        'approvedBy',
        'assignedUserId',
        'branchId',
        'confirmedAt',
        'costCenter',
        'createdAt',
        'currency',
        'customerId',
        'dateRequested',
        'departDate',
        'destination',
        'dzPaymentDate',
        'dzPaymentReference',
        'dzPaymentStatus',
        'generalLedgerAccount',
        'id',
        'invoiceReceiptNumber',
        'itineraryService',
        'notes',
        'pax',
        'pnr',
        'productType',
        'reference',
        'returnDate',
        'status',
        'supplierId',
        'totalAmount',
        'travelerName',
        'tripName',
        'tripReason',
        'updatedAt'
    ];
    $columns = BookingSchema.$columns;
}
_ts_decorate([
    column()
], BookingSchema.prototype, "amountPaidByDz", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "approvedBy", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "assignedUserId", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime()
], BookingSchema.prototype, "confirmedAt", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "costCenter", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], BookingSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "currency", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "customerId", void 0);
_ts_decorate([
    column.date()
], BookingSchema.prototype, "dateRequested", void 0);
_ts_decorate([
    column.date()
], BookingSchema.prototype, "departDate", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "destination", void 0);
_ts_decorate([
    column.date()
], BookingSchema.prototype, "dzPaymentDate", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "dzPaymentReference", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "dzPaymentStatus", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "generalLedgerAccount", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], BookingSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "invoiceReceiptNumber", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "itineraryService", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "notes", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "pax", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "pnr", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "productType", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "reference", void 0);
_ts_decorate([
    column.date()
], BookingSchema.prototype, "returnDate", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "status", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "supplierId", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "totalAmount", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "travelerName", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "tripName", void 0);
_ts_decorate([
    column()
], BookingSchema.prototype, "tripReason", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], BookingSchema.prototype, "updatedAt", void 0);
export class BookingItemSchema extends BaseModel {
    static $columns = [
        'bookingId',
        'createdAt',
        'description',
        'id',
        'lineTotal',
        'quantity',
        'supplierId',
        'unitPrice',
        'updatedAt'
    ];
    $columns = BookingItemSchema.$columns;
}
_ts_decorate([
    column()
], BookingItemSchema.prototype, "bookingId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], BookingItemSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], BookingItemSchema.prototype, "description", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], BookingItemSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], BookingItemSchema.prototype, "lineTotal", void 0);
_ts_decorate([
    column()
], BookingItemSchema.prototype, "quantity", void 0);
_ts_decorate([
    column()
], BookingItemSchema.prototype, "supplierId", void 0);
_ts_decorate([
    column()
], BookingItemSchema.prototype, "unitPrice", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], BookingItemSchema.prototype, "updatedAt", void 0);
export class BranchSchema extends BaseModel {
    static $columns = [
        'code',
        'createdAt',
        'id',
        'name',
        'updatedAt'
    ];
    $columns = BranchSchema.$columns;
}
_ts_decorate([
    column()
], BranchSchema.prototype, "code", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], BranchSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], BranchSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], BranchSchema.prototype, "name", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], BranchSchema.prototype, "updatedAt", void 0);
export class ClientAccountSchema extends BaseModel {
    static $columns = [
        'createdAt',
        'customerId',
        'email',
        'fullName',
        'id',
        'isActive',
        'lastLoginAt',
        'password',
        'privileges',
        'role',
        'updatedAt'
    ];
    $columns = ClientAccountSchema.$columns;
}
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], ClientAccountSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], ClientAccountSchema.prototype, "customerId", void 0);
_ts_decorate([
    column()
], ClientAccountSchema.prototype, "email", void 0);
_ts_decorate([
    column()
], ClientAccountSchema.prototype, "fullName", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], ClientAccountSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], ClientAccountSchema.prototype, "isActive", void 0);
_ts_decorate([
    column.dateTime()
], ClientAccountSchema.prototype, "lastLoginAt", void 0);
_ts_decorate([
    column({
        serializeAs: null
    })
], ClientAccountSchema.prototype, "password", void 0);
_ts_decorate([
    column()
], ClientAccountSchema.prototype, "privileges", void 0);
_ts_decorate([
    column()
], ClientAccountSchema.prototype, "role", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], ClientAccountSchema.prototype, "updatedAt", void 0);
export class CustomerSchema extends BaseModel {
    static $columns = [
        'branchId',
        'company',
        'createdAt',
        'email',
        'fullName',
        'id',
        'notes',
        'phone',
        'updatedAt'
    ];
    $columns = CustomerSchema.$columns;
}
_ts_decorate([
    column()
], CustomerSchema.prototype, "branchId", void 0);
_ts_decorate([
    column()
], CustomerSchema.prototype, "company", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], CustomerSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], CustomerSchema.prototype, "email", void 0);
_ts_decorate([
    column()
], CustomerSchema.prototype, "fullName", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], CustomerSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], CustomerSchema.prototype, "notes", void 0);
_ts_decorate([
    column()
], CustomerSchema.prototype, "phone", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], CustomerSchema.prototype, "updatedAt", void 0);
export class DocumentSchema extends BaseModel {
    static $columns = [
        'branchId',
        'createdAt',
        'documentType',
        'filePath',
        'fileSize',
        'id',
        'mimeType',
        'referenceId',
        'referenceType',
        'status',
        'title',
        'updatedAt',
        'uploadedById'
    ];
    $columns = DocumentSchema.$columns;
}
_ts_decorate([
    column()
], DocumentSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], DocumentSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], DocumentSchema.prototype, "documentType", void 0);
_ts_decorate([
    column()
], DocumentSchema.prototype, "filePath", void 0);
_ts_decorate([
    column()
], DocumentSchema.prototype, "fileSize", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], DocumentSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], DocumentSchema.prototype, "mimeType", void 0);
_ts_decorate([
    column()
], DocumentSchema.prototype, "referenceId", void 0);
_ts_decorate([
    column()
], DocumentSchema.prototype, "referenceType", void 0);
_ts_decorate([
    column()
], DocumentSchema.prototype, "status", void 0);
_ts_decorate([
    column()
], DocumentSchema.prototype, "title", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], DocumentSchema.prototype, "updatedAt", void 0);
_ts_decorate([
    column()
], DocumentSchema.prototype, "uploadedById", void 0);
export class InvoiceSchema extends BaseModel {
    static $columns = [
        'amountPaid',
        'bookingId',
        'branchId',
        'createdAt',
        'currency',
        'customerId',
        'documentId',
        'dueDate',
        'id',
        'invoiceNumber',
        'issueDate',
        'notes',
        'recoveryReportItemId',
        'status',
        'subtotal',
        'taxAmount',
        'totalAmount',
        'updatedAt'
    ];
    $columns = InvoiceSchema.$columns;
}
_ts_decorate([
    column()
], InvoiceSchema.prototype, "amountPaid", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "bookingId", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], InvoiceSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "currency", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "customerId", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "documentId", void 0);
_ts_decorate([
    column.date()
], InvoiceSchema.prototype, "dueDate", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], InvoiceSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "invoiceNumber", void 0);
_ts_decorate([
    column.date()
], InvoiceSchema.prototype, "issueDate", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "notes", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "recoveryReportItemId", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "status", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "subtotal", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "taxAmount", void 0);
_ts_decorate([
    column()
], InvoiceSchema.prototype, "totalAmount", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], InvoiceSchema.prototype, "updatedAt", void 0);
export class NotificationSchema extends BaseModel {
    static $columns = [
        'body',
        'createdAt',
        'entityId',
        'entityType',
        'id',
        'readAt',
        'title',
        'type',
        'userId'
    ];
    $columns = NotificationSchema.$columns;
}
_ts_decorate([
    column()
], NotificationSchema.prototype, "body", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], NotificationSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], NotificationSchema.prototype, "entityId", void 0);
_ts_decorate([
    column()
], NotificationSchema.prototype, "entityType", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], NotificationSchema.prototype, "id", void 0);
_ts_decorate([
    column.dateTime()
], NotificationSchema.prototype, "readAt", void 0);
_ts_decorate([
    column()
], NotificationSchema.prototype, "title", void 0);
_ts_decorate([
    column()
], NotificationSchema.prototype, "type", void 0);
_ts_decorate([
    column()
], NotificationSchema.prototype, "userId", void 0);
export class PaymentRecordSchema extends BaseModel {
    static $columns = [
        'amount',
        'branchId',
        'createdAt',
        'currency',
        'customerId',
        'documentId',
        'id',
        'invoiceId',
        'notes',
        'paymentDate',
        'paymentMethod',
        'paymentReference',
        'receiptId',
        'recordedById',
        'reference',
        'status',
        'updatedAt'
    ];
    $columns = PaymentRecordSchema.$columns;
}
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "amount", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], PaymentRecordSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "currency", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "customerId", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "documentId", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], PaymentRecordSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "invoiceId", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "notes", void 0);
_ts_decorate([
    column.date()
], PaymentRecordSchema.prototype, "paymentDate", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "paymentMethod", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "paymentReference", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "receiptId", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "recordedById", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "reference", void 0);
_ts_decorate([
    column()
], PaymentRecordSchema.prototype, "status", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], PaymentRecordSchema.prototype, "updatedAt", void 0);
export class QuotationSchema extends BaseModel {
    static $columns = [
        'approvedAt',
        'bookingId',
        'branchId',
        'createdAt',
        'createdById',
        'currency',
        'customerId',
        'documentId',
        'id',
        'notes',
        'reference',
        'status',
        'subtotal',
        'taxAmount',
        'totalAmount',
        'updatedAt',
        'validUntil'
    ];
    $columns = QuotationSchema.$columns;
}
_ts_decorate([
    column.dateTime()
], QuotationSchema.prototype, "approvedAt", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "bookingId", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], QuotationSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "createdById", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "currency", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "customerId", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "documentId", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], QuotationSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "notes", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "reference", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "status", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "subtotal", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "taxAmount", void 0);
_ts_decorate([
    column()
], QuotationSchema.prototype, "totalAmount", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], QuotationSchema.prototype, "updatedAt", void 0);
_ts_decorate([
    column.date()
], QuotationSchema.prototype, "validUntil", void 0);
export class ReceiptSchema extends BaseModel {
    static $columns = [
        'amount',
        'branchId',
        'createdAt',
        'currency',
        'customerId',
        'documentId',
        'id',
        'invoiceId',
        'notes',
        'paymentMethod',
        'paymentReference',
        'receiptNumber',
        'receivedDate',
        'recordedById',
        'updatedAt'
    ];
    $columns = ReceiptSchema.$columns;
}
_ts_decorate([
    column()
], ReceiptSchema.prototype, "amount", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], ReceiptSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "currency", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "customerId", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "documentId", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], ReceiptSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "invoiceId", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "notes", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "paymentMethod", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "paymentReference", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "receiptNumber", void 0);
_ts_decorate([
    column.date()
], ReceiptSchema.prototype, "receivedDate", void 0);
_ts_decorate([
    column()
], ReceiptSchema.prototype, "recordedById", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], ReceiptSchema.prototype, "updatedAt", void 0);
export class RecoveryReportSchema extends BaseModel {
    static $columns = [
        'approvedAt',
        'branchId',
        'createdAt',
        'createdById',
        'currency',
        'customerId',
        'id',
        'recoveredAt',
        'reportPeriodEnd',
        'reportPeriodStart',
        'reportReference',
        'reportType',
        'sentAt',
        'status',
        'totalAmount',
        'updatedAt'
    ];
    $columns = RecoveryReportSchema.$columns;
}
_ts_decorate([
    column.dateTime()
], RecoveryReportSchema.prototype, "approvedAt", void 0);
_ts_decorate([
    column()
], RecoveryReportSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], RecoveryReportSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], RecoveryReportSchema.prototype, "createdById", void 0);
_ts_decorate([
    column()
], RecoveryReportSchema.prototype, "currency", void 0);
_ts_decorate([
    column()
], RecoveryReportSchema.prototype, "customerId", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], RecoveryReportSchema.prototype, "id", void 0);
_ts_decorate([
    column.dateTime()
], RecoveryReportSchema.prototype, "recoveredAt", void 0);
_ts_decorate([
    column.date()
], RecoveryReportSchema.prototype, "reportPeriodEnd", void 0);
_ts_decorate([
    column.date()
], RecoveryReportSchema.prototype, "reportPeriodStart", void 0);
_ts_decorate([
    column()
], RecoveryReportSchema.prototype, "reportReference", void 0);
_ts_decorate([
    column()
], RecoveryReportSchema.prototype, "reportType", void 0);
_ts_decorate([
    column.dateTime()
], RecoveryReportSchema.prototype, "sentAt", void 0);
_ts_decorate([
    column()
], RecoveryReportSchema.prototype, "status", void 0);
_ts_decorate([
    column()
], RecoveryReportSchema.prototype, "totalAmount", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], RecoveryReportSchema.prototype, "updatedAt", void 0);
export class RecoveryReportAuditLogSchema extends BaseModel {
    static $columns = [
        'action',
        'description',
        'id',
        'newStatus',
        'oldStatus',
        'performedAt',
        'performedByClientId',
        'performedByUserId',
        'recoveryReportItemId'
    ];
    $columns = RecoveryReportAuditLogSchema.$columns;
}
_ts_decorate([
    column()
], RecoveryReportAuditLogSchema.prototype, "action", void 0);
_ts_decorate([
    column()
], RecoveryReportAuditLogSchema.prototype, "description", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], RecoveryReportAuditLogSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], RecoveryReportAuditLogSchema.prototype, "newStatus", void 0);
_ts_decorate([
    column()
], RecoveryReportAuditLogSchema.prototype, "oldStatus", void 0);
_ts_decorate([
    column.dateTime()
], RecoveryReportAuditLogSchema.prototype, "performedAt", void 0);
_ts_decorate([
    column()
], RecoveryReportAuditLogSchema.prototype, "performedByClientId", void 0);
_ts_decorate([
    column()
], RecoveryReportAuditLogSchema.prototype, "performedByUserId", void 0);
_ts_decorate([
    column()
], RecoveryReportAuditLogSchema.prototype, "recoveryReportItemId", void 0);
export class RecoveryReportItemSchema extends BaseModel {
    static $columns = [
        'amountPaidByDz',
        'approvedBy',
        'bookingId',
        'branchId',
        'clientApprovedAt',
        'clientQuery',
        'clientReviewedAt',
        'costCenter',
        'createdAt',
        'createdById',
        'currency',
        'customerId',
        'dateRequested',
        'dzPaymentDate',
        'dzPaymentReference',
        'dzPaymentStatus',
        'generalLedgerAccount',
        'id',
        'invoiceReceiptNumber',
        'itineraryService',
        'pnr',
        'price',
        'productType',
        'recoveredAt',
        'recoveryReference',
        'recoveryReportId',
        'recoveryStatus',
        'rejectionReason',
        'sentToClientAt',
        'supplierId',
        'supplierInvoiceDocumentId',
        'supplierName',
        'travelEnd',
        'travelStart',
        'travelerName',
        'tripName',
        'tripReason',
        'updatedAt',
        'updatedById'
    ];
    $columns = RecoveryReportItemSchema.$columns;
}
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "amountPaidByDz", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "approvedBy", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "bookingId", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime()
], RecoveryReportItemSchema.prototype, "clientApprovedAt", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "clientQuery", void 0);
_ts_decorate([
    column.dateTime()
], RecoveryReportItemSchema.prototype, "clientReviewedAt", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "costCenter", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], RecoveryReportItemSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "createdById", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "currency", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "customerId", void 0);
_ts_decorate([
    column.date()
], RecoveryReportItemSchema.prototype, "dateRequested", void 0);
_ts_decorate([
    column.date()
], RecoveryReportItemSchema.prototype, "dzPaymentDate", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "dzPaymentReference", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "dzPaymentStatus", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "generalLedgerAccount", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], RecoveryReportItemSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "invoiceReceiptNumber", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "itineraryService", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "pnr", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "price", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "productType", void 0);
_ts_decorate([
    column.dateTime()
], RecoveryReportItemSchema.prototype, "recoveredAt", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "recoveryReference", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "recoveryReportId", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "recoveryStatus", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "rejectionReason", void 0);
_ts_decorate([
    column.dateTime()
], RecoveryReportItemSchema.prototype, "sentToClientAt", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "supplierId", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "supplierInvoiceDocumentId", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "supplierName", void 0);
_ts_decorate([
    column.date()
], RecoveryReportItemSchema.prototype, "travelEnd", void 0);
_ts_decorate([
    column.date()
], RecoveryReportItemSchema.prototype, "travelStart", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "travelerName", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "tripName", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "tripReason", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], RecoveryReportItemSchema.prototype, "updatedAt", void 0);
_ts_decorate([
    column()
], RecoveryReportItemSchema.prototype, "updatedById", void 0);
export class RecoveryScheduleSchema extends BaseModel {
    static $columns = [
        'assignedOfficerId',
        'branchId',
        'createdAt',
        'customerId',
        'documentId',
        'escalationLevel',
        'id',
        'invoiceId',
        'nextActionDate',
        'notes',
        'resolvedAt',
        'status',
        'updatedAt'
    ];
    $columns = RecoveryScheduleSchema.$columns;
}
_ts_decorate([
    column()
], RecoveryScheduleSchema.prototype, "assignedOfficerId", void 0);
_ts_decorate([
    column()
], RecoveryScheduleSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], RecoveryScheduleSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], RecoveryScheduleSchema.prototype, "customerId", void 0);
_ts_decorate([
    column()
], RecoveryScheduleSchema.prototype, "documentId", void 0);
_ts_decorate([
    column()
], RecoveryScheduleSchema.prototype, "escalationLevel", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], RecoveryScheduleSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], RecoveryScheduleSchema.prototype, "invoiceId", void 0);
_ts_decorate([
    column.date()
], RecoveryScheduleSchema.prototype, "nextActionDate", void 0);
_ts_decorate([
    column()
], RecoveryScheduleSchema.prototype, "notes", void 0);
_ts_decorate([
    column.dateTime()
], RecoveryScheduleSchema.prototype, "resolvedAt", void 0);
_ts_decorate([
    column()
], RecoveryScheduleSchema.prototype, "status", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], RecoveryScheduleSchema.prototype, "updatedAt", void 0);
export class ReportRunSchema extends BaseModel {
    static $columns = [
        'createdAt',
        'errorMessage',
        'generatedById',
        'id',
        'outputDocumentId',
        'parameters',
        'status',
        'templateId',
        'updatedAt'
    ];
    $columns = ReportRunSchema.$columns;
}
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], ReportRunSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], ReportRunSchema.prototype, "errorMessage", void 0);
_ts_decorate([
    column()
], ReportRunSchema.prototype, "generatedById", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], ReportRunSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], ReportRunSchema.prototype, "outputDocumentId", void 0);
_ts_decorate([
    column()
], ReportRunSchema.prototype, "parameters", void 0);
_ts_decorate([
    column()
], ReportRunSchema.prototype, "status", void 0);
_ts_decorate([
    column()
], ReportRunSchema.prototype, "templateId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], ReportRunSchema.prototype, "updatedAt", void 0);
export class ReportTemplateSchema extends BaseModel {
    static $columns = [
        'createdAt',
        'description',
        'filePath',
        'id',
        'isActive',
        'name',
        'slug',
        'source',
        'updatedAt'
    ];
    $columns = ReportTemplateSchema.$columns;
}
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], ReportTemplateSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], ReportTemplateSchema.prototype, "description", void 0);
_ts_decorate([
    column()
], ReportTemplateSchema.prototype, "filePath", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], ReportTemplateSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], ReportTemplateSchema.prototype, "isActive", void 0);
_ts_decorate([
    column()
], ReportTemplateSchema.prototype, "name", void 0);
_ts_decorate([
    column()
], ReportTemplateSchema.prototype, "slug", void 0);
_ts_decorate([
    column()
], ReportTemplateSchema.prototype, "source", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], ReportTemplateSchema.prototype, "updatedAt", void 0);
export class RolePermissionSchema extends BaseModel {
    static $columns = [
        'createdAt',
        'id',
        'permission',
        'role',
        'updatedAt'
    ];
    $columns = RolePermissionSchema.$columns;
}
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], RolePermissionSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], RolePermissionSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], RolePermissionSchema.prototype, "permission", void 0);
_ts_decorate([
    column()
], RolePermissionSchema.prototype, "role", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], RolePermissionSchema.prototype, "updatedAt", void 0);
export class SupplierSchema extends BaseModel {
    static $columns = [
        'branchId',
        'code',
        'contactName',
        'createdAt',
        'email',
        'id',
        'isActive',
        'name',
        'notes',
        'phone',
        'updatedAt'
    ];
    $columns = SupplierSchema.$columns;
}
_ts_decorate([
    column()
], SupplierSchema.prototype, "branchId", void 0);
_ts_decorate([
    column()
], SupplierSchema.prototype, "code", void 0);
_ts_decorate([
    column()
], SupplierSchema.prototype, "contactName", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], SupplierSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], SupplierSchema.prototype, "email", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], SupplierSchema.prototype, "id", void 0);
_ts_decorate([
    column()
], SupplierSchema.prototype, "isActive", void 0);
_ts_decorate([
    column()
], SupplierSchema.prototype, "name", void 0);
_ts_decorate([
    column()
], SupplierSchema.prototype, "notes", void 0);
_ts_decorate([
    column()
], SupplierSchema.prototype, "phone", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], SupplierSchema.prototype, "updatedAt", void 0);
export class UserSchema extends BaseModel {
    static $columns = [
        'branchId',
        'createdAt',
        'email',
        'fullName',
        'id',
        'lastAccessedAt',
        'password',
        'role',
        'updatedAt'
    ];
    $columns = UserSchema.$columns;
}
_ts_decorate([
    column()
], UserSchema.prototype, "branchId", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true
    })
], UserSchema.prototype, "createdAt", void 0);
_ts_decorate([
    column()
], UserSchema.prototype, "email", void 0);
_ts_decorate([
    column()
], UserSchema.prototype, "fullName", void 0);
_ts_decorate([
    column({
        isPrimary: true
    })
], UserSchema.prototype, "id", void 0);
_ts_decorate([
    column.dateTime()
], UserSchema.prototype, "lastAccessedAt", void 0);
_ts_decorate([
    column({
        serializeAs: null
    })
], UserSchema.prototype, "password", void 0);
_ts_decorate([
    column()
], UserSchema.prototype, "role", void 0);
_ts_decorate([
    column.dateTime({
        autoCreate: true,
        autoUpdate: true
    })
], UserSchema.prototype, "updatedAt", void 0);
