import { Form, Link } from '@adonisjs/inertia/react'
import { DownloadIcon, ReportsIcon } from '~/components/icons'
import { tableIconButtonClass } from '~/components/ui/table_icon_button'
import { Badge } from '~/components/ui/badge'
import { Button } from '~/components/ui/button'
import { Card, CardBody, CardHeader } from '~/components/ui/card'
import { Table, TBody, TD, THead, TH, TR } from '~/components/ui/table'
import { stopRowClickProps } from '~/lib/table_row'
import { formatStatusLabel } from '~/lib/format'
import { statusTone } from '~/lib/status_tone'

type ReportsIndexProps = {
  templates: Array<{
    id: number
    name: string
    slug: string
    source: string
    description: string | null
  }>
  recentRuns: Array<{
    id: number
    templateName: string
    status: string
    generatedBy: string
    createdAt: string
    outputDocumentId: number | null
  }>
  canExport: boolean
  canManageTemplates: boolean
}

export default function ReportsIndex({
  templates,
  recentRuns,
  canExport,
  canManageTemplates,
}: ReportsIndexProps) {
  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold text-slate-900">Reports</h1>
          <p className="mt-1 text-sm text-slate-600">
            Generate and download agency reports from system templates.
          </p>
        </div>
        {canManageTemplates ? (
          <Link
            route="reports.templates"
            className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 text-sm font-medium text-slate-700 hover:bg-slate-50"
          >
            <ReportsIcon />
            Manage templates
          </Link>
        ) : null}
      </div>

      <Card>
        <CardHeader
          title="Report templates"
          description={`${templates.length} template${templates.length === 1 ? '' : 's'} available`}
        />
        {templates.length === 0 ? (
          <CardBody>
            <p className="text-sm text-slate-600">No report templates configured.</p>
          </CardBody>
        ) : (
          <CardBody className="space-y-4 p-0">
            {templates.map((template) => (
              <div
                key={template.id}
                className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 px-6 py-4 last:border-b-0"
              >
                <div>
                  <p className="font-medium text-slate-900">{template.name}</p>
                  {template.description ? (
                    <p className="mt-0.5 text-sm text-slate-600">{template.description}</p>
                  ) : null}
                  <p className="mt-1 text-xs text-slate-500">{template.slug} · {template.source}</p>
                </div>
                {canExport ? (
                  <Form route="reports.run" className="shrink-0">
                    <input type="hidden" name="templateId" value={template.id} />
                    <Button type="submit" size="sm">Run report</Button>
                  </Form>
                ) : null}
              </div>
            ))}
          </CardBody>
        )}
      </Card>

      <Card>
        <CardHeader
          title="Recent runs"
          description={`${recentRuns.length} recent run${recentRuns.length === 1 ? '' : 's'}`}
        />
        {recentRuns.length === 0 ? (
          <CardBody>
            <p className="text-sm text-slate-600">No reports have been generated yet.</p>
          </CardBody>
        ) : (
          <CardBody className="p-0">
            <Table scrollContainer={false}>
              <THead>
                <TR>
                  <TH>Template</TH>
                  <TH>Status</TH>
                  <TH>Generated by</TH>
                  <TH>Created</TH>
                  <TH><span className="sr-only">Download</span></TH>
                </TR>
              </THead>
              <TBody>
                {recentRuns.map((run) => (
                  <TR
                    key={run.id}
                    href={run.outputDocumentId ? `/reports/runs/${run.id}/download` : undefined}
                  >
                    <TD className="font-medium text-slate-900">{run.templateName}</TD>
                    <TD>
                      <Badge tone={statusTone(run.status)}>{formatStatusLabel(run.status)}</Badge>
                    </TD>
                    <TD className="text-slate-600">{run.generatedBy}</TD>
                    <TD className="text-slate-600">{run.createdAt}</TD>
                    <TD {...stopRowClickProps}>
                      {run.outputDocumentId ? (
                        <a
                          href={`/reports/runs/${run.id}/download`}
                          className={tableIconButtonClass('secondary')}
                          title="Download report"
                          aria-label="Download report"
                        >
                          <DownloadIcon className="h-4 w-4" />
                        </a>
                      ) : (
                        <span className="text-sm text-slate-400">—</span>
                      )}
                    </TD>
                  </TR>
                ))}
              </TBody>
            </Table>
          </CardBody>
        )}
      </Card>
    </div>
  )
}
