/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['home']['types'],
  },
  'legal.eula': {
    methods: ["GET","HEAD"],
    pattern: '/legal/eula',
    tokens: [{"old":"/legal/eula","type":0,"val":"legal","end":""},{"old":"/legal/eula","type":0,"val":"eula","end":""}],
    types: placeholder as Registry['legal.eula']['types'],
  },
  'legal.privacy': {
    methods: ["GET","HEAD"],
    pattern: '/legal/privacy',
    tokens: [{"old":"/legal/privacy","type":0,"val":"legal","end":""},{"old":"/legal/privacy","type":0,"val":"privacy","end":""}],
    types: placeholder as Registry['legal.privacy']['types'],
  },
  'portal.login': {
    methods: ["GET","HEAD"],
    pattern: '/portal/login',
    tokens: [{"old":"/portal/login","type":0,"val":"portal","end":""},{"old":"/portal/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['portal.login']['types'],
  },
  'portal.login.store': {
    methods: ["POST"],
    pattern: '/portal/login',
    tokens: [{"old":"/portal/login","type":0,"val":"portal","end":""},{"old":"/portal/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['portal.login.store']['types'],
  },
  'portal.register': {
    methods: ["GET","HEAD"],
    pattern: '/portal/register',
    tokens: [{"old":"/portal/register","type":0,"val":"portal","end":""},{"old":"/portal/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['portal.register']['types'],
  },
  'portal.register.store': {
    methods: ["POST"],
    pattern: '/portal/register',
    tokens: [{"old":"/portal/register","type":0,"val":"portal","end":""},{"old":"/portal/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['portal.register.store']['types'],
  },
  'portal.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/portal/dashboard',
    tokens: [{"old":"/portal/dashboard","type":0,"val":"portal","end":""},{"old":"/portal/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['portal.dashboard']['types'],
  },
  'portal.enquiries.index': {
    methods: ["GET","HEAD"],
    pattern: '/portal/enquiries',
    tokens: [{"old":"/portal/enquiries","type":0,"val":"portal","end":""},{"old":"/portal/enquiries","type":0,"val":"enquiries","end":""}],
    types: placeholder as Registry['portal.enquiries.index']['types'],
  },
  'portal.enquiries.show': {
    methods: ["GET","HEAD"],
    pattern: '/portal/enquiries/:id',
    tokens: [{"old":"/portal/enquiries/:id","type":0,"val":"portal","end":""},{"old":"/portal/enquiries/:id","type":0,"val":"enquiries","end":""},{"old":"/portal/enquiries/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['portal.enquiries.show']['types'],
  },
  'portal.enquiries.download': {
    methods: ["GET","HEAD"],
    pattern: '/portal/enquiries/:id/download',
    tokens: [{"old":"/portal/enquiries/:id/download","type":0,"val":"portal","end":""},{"old":"/portal/enquiries/:id/download","type":0,"val":"enquiries","end":""},{"old":"/portal/enquiries/:id/download","type":1,"val":"id","end":""},{"old":"/portal/enquiries/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['portal.enquiries.download']['types'],
  },
  'portal.enquiries.cancel': {
    methods: ["POST"],
    pattern: '/portal/enquiries/:id/cancel',
    tokens: [{"old":"/portal/enquiries/:id/cancel","type":0,"val":"portal","end":""},{"old":"/portal/enquiries/:id/cancel","type":0,"val":"enquiries","end":""},{"old":"/portal/enquiries/:id/cancel","type":1,"val":"id","end":""},{"old":"/portal/enquiries/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['portal.enquiries.cancel']['types'],
  },
  'portal.bookings.index': {
    methods: ["GET","HEAD"],
    pattern: '/portal/bookings',
    tokens: [{"old":"/portal/bookings","type":0,"val":"portal","end":""},{"old":"/portal/bookings","type":0,"val":"bookings","end":""}],
    types: placeholder as Registry['portal.bookings.index']['types'],
  },
  'portal.bookings.create': {
    methods: ["GET","HEAD"],
    pattern: '/portal/bookings/create',
    tokens: [{"old":"/portal/bookings/create","type":0,"val":"portal","end":""},{"old":"/portal/bookings/create","type":0,"val":"bookings","end":""},{"old":"/portal/bookings/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['portal.bookings.create']['types'],
  },
  'portal.bookings.cart.add': {
    methods: ["POST"],
    pattern: '/portal/bookings/cart',
    tokens: [{"old":"/portal/bookings/cart","type":0,"val":"portal","end":""},{"old":"/portal/bookings/cart","type":0,"val":"bookings","end":""},{"old":"/portal/bookings/cart","type":0,"val":"cart","end":""}],
    types: placeholder as Registry['portal.bookings.cart.add']['types'],
  },
  'portal.bookings.cart.remove': {
    methods: ["POST"],
    pattern: '/portal/bookings/cart/:itemId/remove',
    tokens: [{"old":"/portal/bookings/cart/:itemId/remove","type":0,"val":"portal","end":""},{"old":"/portal/bookings/cart/:itemId/remove","type":0,"val":"bookings","end":""},{"old":"/portal/bookings/cart/:itemId/remove","type":0,"val":"cart","end":""},{"old":"/portal/bookings/cart/:itemId/remove","type":1,"val":"itemId","end":""},{"old":"/portal/bookings/cart/:itemId/remove","type":0,"val":"remove","end":""}],
    types: placeholder as Registry['portal.bookings.cart.remove']['types'],
  },
  'portal.bookings.cart.budget': {
    methods: ["POST"],
    pattern: '/portal/bookings/cart/:itemId/budget',
    tokens: [{"old":"/portal/bookings/cart/:itemId/budget","type":0,"val":"portal","end":""},{"old":"/portal/bookings/cart/:itemId/budget","type":0,"val":"bookings","end":""},{"old":"/portal/bookings/cart/:itemId/budget","type":0,"val":"cart","end":""},{"old":"/portal/bookings/cart/:itemId/budget","type":1,"val":"itemId","end":""},{"old":"/portal/bookings/cart/:itemId/budget","type":0,"val":"budget","end":""}],
    types: placeholder as Registry['portal.bookings.cart.budget']['types'],
  },
  'portal.bookings.submit': {
    methods: ["POST"],
    pattern: '/portal/bookings/submit',
    tokens: [{"old":"/portal/bookings/submit","type":0,"val":"portal","end":""},{"old":"/portal/bookings/submit","type":0,"val":"bookings","end":""},{"old":"/portal/bookings/submit","type":0,"val":"submit","end":""}],
    types: placeholder as Registry['portal.bookings.submit']['types'],
  },
  'portal.bookings.store': {
    methods: ["POST"],
    pattern: '/portal/bookings',
    tokens: [{"old":"/portal/bookings","type":0,"val":"portal","end":""},{"old":"/portal/bookings","type":0,"val":"bookings","end":""}],
    types: placeholder as Registry['portal.bookings.store']['types'],
  },
  'portal.bookings.show': {
    methods: ["GET","HEAD"],
    pattern: '/portal/bookings/:id',
    tokens: [{"old":"/portal/bookings/:id","type":0,"val":"portal","end":""},{"old":"/portal/bookings/:id","type":0,"val":"bookings","end":""},{"old":"/portal/bookings/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['portal.bookings.show']['types'],
  },
  'portal.quotations.index': {
    methods: ["GET","HEAD"],
    pattern: '/portal/quotations',
    tokens: [{"old":"/portal/quotations","type":0,"val":"portal","end":""},{"old":"/portal/quotations","type":0,"val":"quotations","end":""}],
    types: placeholder as Registry['portal.quotations.index']['types'],
  },
  'portal.quotations.show': {
    methods: ["GET","HEAD"],
    pattern: '/portal/quotations/:id',
    tokens: [{"old":"/portal/quotations/:id","type":0,"val":"portal","end":""},{"old":"/portal/quotations/:id","type":0,"val":"quotations","end":""},{"old":"/portal/quotations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['portal.quotations.show']['types'],
  },
  'portal.quotations.download': {
    methods: ["GET","HEAD"],
    pattern: '/portal/quotations/:id/download',
    tokens: [{"old":"/portal/quotations/:id/download","type":0,"val":"portal","end":""},{"old":"/portal/quotations/:id/download","type":0,"val":"quotations","end":""},{"old":"/portal/quotations/:id/download","type":1,"val":"id","end":""},{"old":"/portal/quotations/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['portal.quotations.download']['types'],
  },
  'portal.quotations.approve': {
    methods: ["POST"],
    pattern: '/portal/quotations/:id/approve',
    tokens: [{"old":"/portal/quotations/:id/approve","type":0,"val":"portal","end":""},{"old":"/portal/quotations/:id/approve","type":0,"val":"quotations","end":""},{"old":"/portal/quotations/:id/approve","type":1,"val":"id","end":""},{"old":"/portal/quotations/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['portal.quotations.approve']['types'],
  },
  'portal.recovery_reports.index': {
    methods: ["GET","HEAD"],
    pattern: '/portal/recovery-reports',
    tokens: [{"old":"/portal/recovery-reports","type":0,"val":"portal","end":""},{"old":"/portal/recovery-reports","type":0,"val":"recovery-reports","end":""}],
    types: placeholder as Registry['portal.recovery_reports.index']['types'],
  },
  'portal.recovery_reports.show': {
    methods: ["GET","HEAD"],
    pattern: '/portal/recovery-reports/:id',
    tokens: [{"old":"/portal/recovery-reports/:id","type":0,"val":"portal","end":""},{"old":"/portal/recovery-reports/:id","type":0,"val":"recovery-reports","end":""},{"old":"/portal/recovery-reports/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['portal.recovery_reports.show']['types'],
  },
  'portal.recovery_reports.approve': {
    methods: ["POST"],
    pattern: '/portal/recovery-reports/:id/approve',
    tokens: [{"old":"/portal/recovery-reports/:id/approve","type":0,"val":"portal","end":""},{"old":"/portal/recovery-reports/:id/approve","type":0,"val":"recovery-reports","end":""},{"old":"/portal/recovery-reports/:id/approve","type":1,"val":"id","end":""},{"old":"/portal/recovery-reports/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['portal.recovery_reports.approve']['types'],
  },
  'portal.recovery_reports.query': {
    methods: ["POST"],
    pattern: '/portal/recovery-reports/:id/query',
    tokens: [{"old":"/portal/recovery-reports/:id/query","type":0,"val":"portal","end":""},{"old":"/portal/recovery-reports/:id/query","type":0,"val":"recovery-reports","end":""},{"old":"/portal/recovery-reports/:id/query","type":1,"val":"id","end":""},{"old":"/portal/recovery-reports/:id/query","type":0,"val":"query","end":""}],
    types: placeholder as Registry['portal.recovery_reports.query']['types'],
  },
  'portal.recovery_reports.reject': {
    methods: ["POST"],
    pattern: '/portal/recovery-reports/:id/reject',
    tokens: [{"old":"/portal/recovery-reports/:id/reject","type":0,"val":"portal","end":""},{"old":"/portal/recovery-reports/:id/reject","type":0,"val":"recovery-reports","end":""},{"old":"/portal/recovery-reports/:id/reject","type":1,"val":"id","end":""},{"old":"/portal/recovery-reports/:id/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['portal.recovery_reports.reject']['types'],
  },
  'portal.recovery_reports.document': {
    methods: ["GET","HEAD"],
    pattern: '/portal/recovery-reports/:id/document',
    tokens: [{"old":"/portal/recovery-reports/:id/document","type":0,"val":"portal","end":""},{"old":"/portal/recovery-reports/:id/document","type":0,"val":"recovery-reports","end":""},{"old":"/portal/recovery-reports/:id/document","type":1,"val":"id","end":""},{"old":"/portal/recovery-reports/:id/document","type":0,"val":"document","end":""}],
    types: placeholder as Registry['portal.recovery_reports.document']['types'],
  },
  'portal.recovery_reports.export': {
    methods: ["GET","HEAD"],
    pattern: '/portal/recovery-reports/export',
    tokens: [{"old":"/portal/recovery-reports/export","type":0,"val":"portal","end":""},{"old":"/portal/recovery-reports/export","type":0,"val":"recovery-reports","end":""},{"old":"/portal/recovery-reports/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['portal.recovery_reports.export']['types'],
  },
  'portal.recovery_reports.export_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/portal/recovery-reports/export-pdf',
    tokens: [{"old":"/portal/recovery-reports/export-pdf","type":0,"val":"portal","end":""},{"old":"/portal/recovery-reports/export-pdf","type":0,"val":"recovery-reports","end":""},{"old":"/portal/recovery-reports/export-pdf","type":0,"val":"export-pdf","end":""}],
    types: placeholder as Registry['portal.recovery_reports.export_pdf']['types'],
  },
  'portal.invoices': {
    methods: ["GET","HEAD"],
    pattern: '/portal/invoices',
    tokens: [{"old":"/portal/invoices","type":0,"val":"portal","end":""},{"old":"/portal/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['portal.invoices']['types'],
  },
  'portal.invoices.show': {
    methods: ["GET","HEAD"],
    pattern: '/portal/invoices/:id',
    tokens: [{"old":"/portal/invoices/:id","type":0,"val":"portal","end":""},{"old":"/portal/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/portal/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['portal.invoices.show']['types'],
  },
  'portal.invoices.download': {
    methods: ["GET","HEAD"],
    pattern: '/portal/invoices/:id/download',
    tokens: [{"old":"/portal/invoices/:id/download","type":0,"val":"portal","end":""},{"old":"/portal/invoices/:id/download","type":0,"val":"invoices","end":""},{"old":"/portal/invoices/:id/download","type":1,"val":"id","end":""},{"old":"/portal/invoices/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['portal.invoices.download']['types'],
  },
  'portal.invoices.pay': {
    methods: ["POST"],
    pattern: '/portal/invoices/:id/pay',
    tokens: [{"old":"/portal/invoices/:id/pay","type":0,"val":"portal","end":""},{"old":"/portal/invoices/:id/pay","type":0,"val":"invoices","end":""},{"old":"/portal/invoices/:id/pay","type":1,"val":"id","end":""},{"old":"/portal/invoices/:id/pay","type":0,"val":"pay","end":""}],
    types: placeholder as Registry['portal.invoices.pay']['types'],
  },
  'portal.users': {
    methods: ["GET","HEAD"],
    pattern: '/portal/users',
    tokens: [{"old":"/portal/users","type":0,"val":"portal","end":""},{"old":"/portal/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['portal.users']['types'],
  },
  'portal.users.create': {
    methods: ["GET","HEAD"],
    pattern: '/portal/users/create',
    tokens: [{"old":"/portal/users/create","type":0,"val":"portal","end":""},{"old":"/portal/users/create","type":0,"val":"users","end":""},{"old":"/portal/users/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['portal.users.create']['types'],
  },
  'portal.users.store': {
    methods: ["POST"],
    pattern: '/portal/users',
    tokens: [{"old":"/portal/users","type":0,"val":"portal","end":""},{"old":"/portal/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['portal.users.store']['types'],
  },
  'portal.users.edit': {
    methods: ["GET","HEAD"],
    pattern: '/portal/users/:id/edit',
    tokens: [{"old":"/portal/users/:id/edit","type":0,"val":"portal","end":""},{"old":"/portal/users/:id/edit","type":0,"val":"users","end":""},{"old":"/portal/users/:id/edit","type":1,"val":"id","end":""},{"old":"/portal/users/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['portal.users.edit']['types'],
  },
  'portal.users.update': {
    methods: ["POST"],
    pattern: '/portal/users/:id',
    tokens: [{"old":"/portal/users/:id","type":0,"val":"portal","end":""},{"old":"/portal/users/:id","type":0,"val":"users","end":""},{"old":"/portal/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['portal.users.update']['types'],
  },
  'portal.logout': {
    methods: ["POST"],
    pattern: '/portal/logout',
    tokens: [{"old":"/portal/logout","type":0,"val":"portal","end":""},{"old":"/portal/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['portal.logout']['types'],
  },
  'session.create': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.create']['types'],
  },
  'session.store': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.store']['types'],
  },
  'session.mfa': {
    methods: ["GET","HEAD"],
    pattern: '/login/mfa',
    tokens: [{"old":"/login/mfa","type":0,"val":"login","end":""},{"old":"/login/mfa","type":0,"val":"mfa","end":""}],
    types: placeholder as Registry['session.mfa']['types'],
  },
  'session.mfa.store': {
    methods: ["POST"],
    pattern: '/login/mfa',
    tokens: [{"old":"/login/mfa","type":0,"val":"login","end":""},{"old":"/login/mfa","type":0,"val":"mfa","end":""}],
    types: placeholder as Registry['session.mfa.store']['types'],
  },
  'settings.quickbooks.callback': {
    methods: ["GET","HEAD"],
    pattern: '/settings/quickbooks/callback',
    tokens: [{"old":"/settings/quickbooks/callback","type":0,"val":"settings","end":""},{"old":"/settings/quickbooks/callback","type":0,"val":"quickbooks","end":""},{"old":"/settings/quickbooks/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['settings.quickbooks.callback']['types'],
  },
  'dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard']['types'],
  },
  'enquiries': {
    methods: ["GET","HEAD"],
    pattern: '/enquiries',
    tokens: [{"old":"/enquiries","type":0,"val":"enquiries","end":""}],
    types: placeholder as Registry['enquiries']['types'],
  },
  'enquiries.show': {
    methods: ["GET","HEAD"],
    pattern: '/enquiries/:id',
    tokens: [{"old":"/enquiries/:id","type":0,"val":"enquiries","end":""},{"old":"/enquiries/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['enquiries.show']['types'],
  },
  'enquiries.download': {
    methods: ["GET","HEAD"],
    pattern: '/enquiries/:id/download',
    tokens: [{"old":"/enquiries/:id/download","type":0,"val":"enquiries","end":""},{"old":"/enquiries/:id/download","type":1,"val":"id","end":""},{"old":"/enquiries/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['enquiries.download']['types'],
  },
  'bookings': {
    methods: ["GET","HEAD"],
    pattern: '/bookings',
    tokens: [{"old":"/bookings","type":0,"val":"bookings","end":""}],
    types: placeholder as Registry['bookings']['types'],
  },
  'bookings.create': {
    methods: ["GET","HEAD"],
    pattern: '/bookings/create',
    tokens: [{"old":"/bookings/create","type":0,"val":"bookings","end":""},{"old":"/bookings/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['bookings.create']['types'],
  },
  'bookings.store': {
    methods: ["POST"],
    pattern: '/bookings',
    tokens: [{"old":"/bookings","type":0,"val":"bookings","end":""}],
    types: placeholder as Registry['bookings.store']['types'],
  },
  'bookings.show': {
    methods: ["GET","HEAD"],
    pattern: '/bookings/:id',
    tokens: [{"old":"/bookings/:id","type":0,"val":"bookings","end":""},{"old":"/bookings/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bookings.show']['types'],
  },
  'workflow_cycles.index': {
    methods: ["GET","HEAD"],
    pattern: '/workflow-cycles',
    tokens: [{"old":"/workflow-cycles","type":0,"val":"workflow-cycles","end":""}],
    types: placeholder as Registry['workflow_cycles.index']['types'],
  },
  'workflow_cycles.show': {
    methods: ["GET","HEAD"],
    pattern: '/workflow-cycles/:id',
    tokens: [{"old":"/workflow-cycles/:id","type":0,"val":"workflow-cycles","end":""},{"old":"/workflow-cycles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['workflow_cycles.show']['types'],
  },
  'portal_booking_types.index': {
    methods: ["GET","HEAD"],
    pattern: '/portal-booking-types',
    tokens: [{"old":"/portal-booking-types","type":0,"val":"portal-booking-types","end":""}],
    types: placeholder as Registry['portal_booking_types.index']['types'],
  },
  'portal_booking_types.create': {
    methods: ["GET","HEAD"],
    pattern: '/portal-booking-types/create',
    tokens: [{"old":"/portal-booking-types/create","type":0,"val":"portal-booking-types","end":""},{"old":"/portal-booking-types/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['portal_booking_types.create']['types'],
  },
  'portal_booking_types.store': {
    methods: ["POST"],
    pattern: '/portal-booking-types',
    tokens: [{"old":"/portal-booking-types","type":0,"val":"portal-booking-types","end":""}],
    types: placeholder as Registry['portal_booking_types.store']['types'],
  },
  'portal_booking_types.edit': {
    methods: ["GET","HEAD"],
    pattern: '/portal-booking-types/:id/edit',
    tokens: [{"old":"/portal-booking-types/:id/edit","type":0,"val":"portal-booking-types","end":""},{"old":"/portal-booking-types/:id/edit","type":1,"val":"id","end":""},{"old":"/portal-booking-types/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['portal_booking_types.edit']['types'],
  },
  'portal_booking_types.update': {
    methods: ["POST"],
    pattern: '/portal-booking-types/:id',
    tokens: [{"old":"/portal-booking-types/:id","type":0,"val":"portal-booking-types","end":""},{"old":"/portal-booking-types/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['portal_booking_types.update']['types'],
  },
  'portal_booking_types.fields.store': {
    methods: ["POST"],
    pattern: '/portal-booking-types/:id/fields',
    tokens: [{"old":"/portal-booking-types/:id/fields","type":0,"val":"portal-booking-types","end":""},{"old":"/portal-booking-types/:id/fields","type":1,"val":"id","end":""},{"old":"/portal-booking-types/:id/fields","type":0,"val":"fields","end":""}],
    types: placeholder as Registry['portal_booking_types.fields.store']['types'],
  },
  'portal_booking_types.fields.update': {
    methods: ["POST"],
    pattern: '/portal-booking-types/:id/fields/:fieldId',
    tokens: [{"old":"/portal-booking-types/:id/fields/:fieldId","type":0,"val":"portal-booking-types","end":""},{"old":"/portal-booking-types/:id/fields/:fieldId","type":1,"val":"id","end":""},{"old":"/portal-booking-types/:id/fields/:fieldId","type":0,"val":"fields","end":""},{"old":"/portal-booking-types/:id/fields/:fieldId","type":1,"val":"fieldId","end":""}],
    types: placeholder as Registry['portal_booking_types.fields.update']['types'],
  },
  'portal_booking_types.fields.destroy': {
    methods: ["POST"],
    pattern: '/portal-booking-types/:id/fields/:fieldId/delete',
    tokens: [{"old":"/portal-booking-types/:id/fields/:fieldId/delete","type":0,"val":"portal-booking-types","end":""},{"old":"/portal-booking-types/:id/fields/:fieldId/delete","type":1,"val":"id","end":""},{"old":"/portal-booking-types/:id/fields/:fieldId/delete","type":0,"val":"fields","end":""},{"old":"/portal-booking-types/:id/fields/:fieldId/delete","type":1,"val":"fieldId","end":""},{"old":"/portal-booking-types/:id/fields/:fieldId/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['portal_booking_types.fields.destroy']['types'],
  },
  'bookings.confirm': {
    methods: ["POST"],
    pattern: '/bookings/:id/confirm',
    tokens: [{"old":"/bookings/:id/confirm","type":0,"val":"bookings","end":""},{"old":"/bookings/:id/confirm","type":1,"val":"id","end":""},{"old":"/bookings/:id/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['bookings.confirm']['types'],
  },
  'bookings.record_supplier_payment': {
    methods: ["POST"],
    pattern: '/bookings/:id/record-supplier-payment',
    tokens: [{"old":"/bookings/:id/record-supplier-payment","type":0,"val":"bookings","end":""},{"old":"/bookings/:id/record-supplier-payment","type":1,"val":"id","end":""},{"old":"/bookings/:id/record-supplier-payment","type":0,"val":"record-supplier-payment","end":""}],
    types: placeholder as Registry['bookings.record_supplier_payment']['types'],
  },
  'bookings.quotations.store': {
    methods: ["POST"],
    pattern: '/bookings/:id/quotations',
    tokens: [{"old":"/bookings/:id/quotations","type":0,"val":"bookings","end":""},{"old":"/bookings/:id/quotations","type":1,"val":"id","end":""},{"old":"/bookings/:id/quotations","type":0,"val":"quotations","end":""}],
    types: placeholder as Registry['bookings.quotations.store']['types'],
  },
  'bookings.create_invoice': {
    methods: ["POST"],
    pattern: '/bookings/:id/create-invoice',
    tokens: [{"old":"/bookings/:id/create-invoice","type":0,"val":"bookings","end":""},{"old":"/bookings/:id/create-invoice","type":1,"val":"id","end":""},{"old":"/bookings/:id/create-invoice","type":0,"val":"create-invoice","end":""}],
    types: placeholder as Registry['bookings.create_invoice']['types'],
  },
  'packages': {
    methods: ["GET","HEAD"],
    pattern: '/packages',
    tokens: [{"old":"/packages","type":0,"val":"packages","end":""}],
    types: placeholder as Registry['packages']['types'],
  },
  'destinations': {
    methods: ["GET","HEAD"],
    pattern: '/destinations',
    tokens: [{"old":"/destinations","type":0,"val":"destinations","end":""}],
    types: placeholder as Registry['destinations']['types'],
  },
  'customers': {
    methods: ["GET","HEAD"],
    pattern: '/customers',
    tokens: [{"old":"/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['customers']['types'],
  },
  'customers.create': {
    methods: ["GET","HEAD"],
    pattern: '/customers/create',
    tokens: [{"old":"/customers/create","type":0,"val":"customers","end":""},{"old":"/customers/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['customers.create']['types'],
  },
  'customers.store': {
    methods: ["POST"],
    pattern: '/customers',
    tokens: [{"old":"/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['customers.store']['types'],
  },
  'customers.show': {
    methods: ["GET","HEAD"],
    pattern: '/customers/:id',
    tokens: [{"old":"/customers/:id","type":0,"val":"customers","end":""},{"old":"/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.show']['types'],
  },
  'offices': {
    methods: ["GET","HEAD"],
    pattern: '/offices',
    tokens: [{"old":"/offices","type":0,"val":"offices","end":""}],
    types: placeholder as Registry['offices']['types'],
  },
  'agents': {
    methods: ["GET","HEAD"],
    pattern: '/agents',
    tokens: [{"old":"/agents","type":0,"val":"agents","end":""}],
    types: placeholder as Registry['agents']['types'],
  },
  'documents': {
    methods: ["GET","HEAD"],
    pattern: '/documents',
    tokens: [{"old":"/documents","type":0,"val":"documents","end":""}],
    types: placeholder as Registry['documents']['types'],
  },
  'documents.store': {
    methods: ["POST"],
    pattern: '/documents',
    tokens: [{"old":"/documents","type":0,"val":"documents","end":""}],
    types: placeholder as Registry['documents.store']['types'],
  },
  'documents.download': {
    methods: ["GET","HEAD"],
    pattern: '/documents/:id/download',
    tokens: [{"old":"/documents/:id/download","type":0,"val":"documents","end":""},{"old":"/documents/:id/download","type":1,"val":"id","end":""},{"old":"/documents/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['documents.download']['types'],
  },
  'documents.destroy': {
    methods: ["DELETE"],
    pattern: '/documents/:id',
    tokens: [{"old":"/documents/:id","type":0,"val":"documents","end":""},{"old":"/documents/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['documents.destroy']['types'],
  },
  'suppliers': {
    methods: ["GET","HEAD"],
    pattern: '/suppliers',
    tokens: [{"old":"/suppliers","type":0,"val":"suppliers","end":""}],
    types: placeholder as Registry['suppliers']['types'],
  },
  'suppliers.create': {
    methods: ["GET","HEAD"],
    pattern: '/suppliers/create',
    tokens: [{"old":"/suppliers/create","type":0,"val":"suppliers","end":""},{"old":"/suppliers/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['suppliers.create']['types'],
  },
  'suppliers.store': {
    methods: ["POST"],
    pattern: '/suppliers',
    tokens: [{"old":"/suppliers","type":0,"val":"suppliers","end":""}],
    types: placeholder as Registry['suppliers.store']['types'],
  },
  'suppliers.show': {
    methods: ["GET","HEAD"],
    pattern: '/suppliers/:id',
    tokens: [{"old":"/suppliers/:id","type":0,"val":"suppliers","end":""},{"old":"/suppliers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['suppliers.show']['types'],
  },
  'quotations': {
    methods: ["GET","HEAD"],
    pattern: '/quotations',
    tokens: [{"old":"/quotations","type":0,"val":"quotations","end":""}],
    types: placeholder as Registry['quotations']['types'],
  },
  'quotations.create': {
    methods: ["GET","HEAD"],
    pattern: '/quotations/create',
    tokens: [{"old":"/quotations/create","type":0,"val":"quotations","end":""},{"old":"/quotations/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['quotations.create']['types'],
  },
  'quotations.store': {
    methods: ["POST"],
    pattern: '/quotations',
    tokens: [{"old":"/quotations","type":0,"val":"quotations","end":""}],
    types: placeholder as Registry['quotations.store']['types'],
  },
  'quotations.show': {
    methods: ["GET","HEAD"],
    pattern: '/quotations/:id',
    tokens: [{"old":"/quotations/:id","type":0,"val":"quotations","end":""},{"old":"/quotations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['quotations.show']['types'],
  },
  'quotations.download': {
    methods: ["GET","HEAD"],
    pattern: '/quotations/:id/download',
    tokens: [{"old":"/quotations/:id/download","type":0,"val":"quotations","end":""},{"old":"/quotations/:id/download","type":1,"val":"id","end":""},{"old":"/quotations/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['quotations.download']['types'],
  },
  'quotations.send': {
    methods: ["POST"],
    pattern: '/quotations/:id/send',
    tokens: [{"old":"/quotations/:id/send","type":0,"val":"quotations","end":""},{"old":"/quotations/:id/send","type":1,"val":"id","end":""},{"old":"/quotations/:id/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['quotations.send']['types'],
  },
  'invoices': {
    methods: ["GET","HEAD"],
    pattern: '/invoices',
    tokens: [{"old":"/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoices']['types'],
  },
  'invoices.create': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/create',
    tokens: [{"old":"/invoices/create","type":0,"val":"invoices","end":""},{"old":"/invoices/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['invoices.create']['types'],
  },
  'invoices.store': {
    methods: ["POST"],
    pattern: '/invoices',
    tokens: [{"old":"/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoices.store']['types'],
  },
  'invoices.show': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/:id',
    tokens: [{"old":"/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoices.show']['types'],
  },
  'invoices.download': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/:id/download',
    tokens: [{"old":"/invoices/:id/download","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/download","type":1,"val":"id","end":""},{"old":"/invoices/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['invoices.download']['types'],
  },
  'invoices.issue': {
    methods: ["POST"],
    pattern: '/invoices/:id/issue',
    tokens: [{"old":"/invoices/:id/issue","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/issue","type":1,"val":"id","end":""},{"old":"/invoices/:id/issue","type":0,"val":"issue","end":""}],
    types: placeholder as Registry['invoices.issue']['types'],
  },
  'invoices.mark_paid': {
    methods: ["POST"],
    pattern: '/invoices/:id/mark-paid',
    tokens: [{"old":"/invoices/:id/mark-paid","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/mark-paid","type":1,"val":"id","end":""},{"old":"/invoices/:id/mark-paid","type":0,"val":"mark-paid","end":""}],
    types: placeholder as Registry['invoices.mark_paid']['types'],
  },
  'quickbooks.accounts': {
    methods: ["GET","HEAD"],
    pattern: '/quickbooks/accounts',
    tokens: [{"old":"/quickbooks/accounts","type":0,"val":"quickbooks","end":""},{"old":"/quickbooks/accounts","type":0,"val":"accounts","end":""}],
    types: placeholder as Registry['quickbooks.accounts']['types'],
  },
  'quickbooks.accounts.refresh': {
    methods: ["POST"],
    pattern: '/quickbooks/accounts/refresh',
    tokens: [{"old":"/quickbooks/accounts/refresh","type":0,"val":"quickbooks","end":""},{"old":"/quickbooks/accounts/refresh","type":0,"val":"accounts","end":""},{"old":"/quickbooks/accounts/refresh","type":0,"val":"refresh","end":""}],
    types: placeholder as Registry['quickbooks.accounts.refresh']['types'],
  },
  'quickbooks.items': {
    methods: ["GET","HEAD"],
    pattern: '/quickbooks/items',
    tokens: [{"old":"/quickbooks/items","type":0,"val":"quickbooks","end":""},{"old":"/quickbooks/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['quickbooks.items']['types'],
  },
  'quickbooks.items.refresh': {
    methods: ["POST"],
    pattern: '/quickbooks/items/refresh',
    tokens: [{"old":"/quickbooks/items/refresh","type":0,"val":"quickbooks","end":""},{"old":"/quickbooks/items/refresh","type":0,"val":"items","end":""},{"old":"/quickbooks/items/refresh","type":0,"val":"refresh","end":""}],
    types: placeholder as Registry['quickbooks.items.refresh']['types'],
  },
  'receipts': {
    methods: ["GET","HEAD"],
    pattern: '/receipts',
    tokens: [{"old":"/receipts","type":0,"val":"receipts","end":""}],
    types: placeholder as Registry['receipts']['types'],
  },
  'receipts.create': {
    methods: ["GET","HEAD"],
    pattern: '/receipts/create',
    tokens: [{"old":"/receipts/create","type":0,"val":"receipts","end":""},{"old":"/receipts/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['receipts.create']['types'],
  },
  'receipts.store': {
    methods: ["POST"],
    pattern: '/receipts',
    tokens: [{"old":"/receipts","type":0,"val":"receipts","end":""}],
    types: placeholder as Registry['receipts.store']['types'],
  },
  'payments': {
    methods: ["GET","HEAD"],
    pattern: '/payments',
    tokens: [{"old":"/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['payments']['types'],
  },
  'payments.create': {
    methods: ["GET","HEAD"],
    pattern: '/payments/create',
    tokens: [{"old":"/payments/create","type":0,"val":"payments","end":""},{"old":"/payments/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['payments.create']['types'],
  },
  'payments.store': {
    methods: ["POST"],
    pattern: '/payments',
    tokens: [{"old":"/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['payments.store']['types'],
  },
  'recovery_reports.index': {
    methods: ["GET","HEAD"],
    pattern: '/recovery-reports',
    tokens: [{"old":"/recovery-reports","type":0,"val":"recovery-reports","end":""}],
    types: placeholder as Registry['recovery_reports.index']['types'],
  },
  'recovery_reports.items.show': {
    methods: ["GET","HEAD"],
    pattern: '/recovery-reports/items/:id',
    tokens: [{"old":"/recovery-reports/items/:id","type":0,"val":"recovery-reports","end":""},{"old":"/recovery-reports/items/:id","type":0,"val":"items","end":""},{"old":"/recovery-reports/items/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recovery_reports.items.show']['types'],
  },
  'recovery_reports.items.send': {
    methods: ["POST"],
    pattern: '/recovery-reports/items/:id/send-to-client',
    tokens: [{"old":"/recovery-reports/items/:id/send-to-client","type":0,"val":"recovery-reports","end":""},{"old":"/recovery-reports/items/:id/send-to-client","type":0,"val":"items","end":""},{"old":"/recovery-reports/items/:id/send-to-client","type":1,"val":"id","end":""},{"old":"/recovery-reports/items/:id/send-to-client","type":0,"val":"send-to-client","end":""}],
    types: placeholder as Registry['recovery_reports.items.send']['types'],
  },
  'recovery_reports.items.mark_recovered': {
    methods: ["POST"],
    pattern: '/recovery-reports/items/:id/mark-recovered',
    tokens: [{"old":"/recovery-reports/items/:id/mark-recovered","type":0,"val":"recovery-reports","end":""},{"old":"/recovery-reports/items/:id/mark-recovered","type":0,"val":"items","end":""},{"old":"/recovery-reports/items/:id/mark-recovered","type":1,"val":"id","end":""},{"old":"/recovery-reports/items/:id/mark-recovered","type":0,"val":"mark-recovered","end":""}],
    types: placeholder as Registry['recovery_reports.items.mark_recovered']['types'],
  },
  'recovery_reports.export': {
    methods: ["GET","HEAD"],
    pattern: '/recovery-reports/export',
    tokens: [{"old":"/recovery-reports/export","type":0,"val":"recovery-reports","end":""},{"old":"/recovery-reports/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['recovery_reports.export']['types'],
  },
  'recovery_reports.export_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/recovery-reports/export-pdf',
    tokens: [{"old":"/recovery-reports/export-pdf","type":0,"val":"recovery-reports","end":""},{"old":"/recovery-reports/export-pdf","type":0,"val":"export-pdf","end":""}],
    types: placeholder as Registry['recovery_reports.export_pdf']['types'],
  },
  'recovery_reports.weekly_export': {
    methods: ["POST"],
    pattern: '/recovery-reports/weekly-export',
    tokens: [{"old":"/recovery-reports/weekly-export","type":0,"val":"recovery-reports","end":""},{"old":"/recovery-reports/weekly-export","type":0,"val":"weekly-export","end":""}],
    types: placeholder as Registry['recovery_reports.weekly_export']['types'],
  },
  'reports': {
    methods: ["GET","HEAD"],
    pattern: '/reports',
    tokens: [{"old":"/reports","type":0,"val":"reports","end":""}],
    types: placeholder as Registry['reports']['types'],
  },
  'reports.templates': {
    methods: ["GET","HEAD"],
    pattern: '/reports/templates',
    tokens: [{"old":"/reports/templates","type":0,"val":"reports","end":""},{"old":"/reports/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['reports.templates']['types'],
  },
  'reports.templates.store': {
    methods: ["POST"],
    pattern: '/reports/templates',
    tokens: [{"old":"/reports/templates","type":0,"val":"reports","end":""},{"old":"/reports/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['reports.templates.store']['types'],
  },
  'reports.run': {
    methods: ["POST"],
    pattern: '/reports/run',
    tokens: [{"old":"/reports/run","type":0,"val":"reports","end":""},{"old":"/reports/run","type":0,"val":"run","end":""}],
    types: placeholder as Registry['reports.run']['types'],
  },
  'reports.download': {
    methods: ["GET","HEAD"],
    pattern: '/reports/runs/:id/download',
    tokens: [{"old":"/reports/runs/:id/download","type":0,"val":"reports","end":""},{"old":"/reports/runs/:id/download","type":0,"val":"runs","end":""},{"old":"/reports/runs/:id/download","type":1,"val":"id","end":""},{"old":"/reports/runs/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['reports.download']['types'],
  },
  'users': {
    methods: ["GET","HEAD"],
    pattern: '/users',
    tokens: [{"old":"/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users']['types'],
  },
  'users.create': {
    methods: ["GET","HEAD"],
    pattern: '/users/create',
    tokens: [{"old":"/users/create","type":0,"val":"users","end":""},{"old":"/users/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['users.create']['types'],
  },
  'users.store': {
    methods: ["POST"],
    pattern: '/users',
    tokens: [{"old":"/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.store']['types'],
  },
  'roles': {
    methods: ["GET","HEAD"],
    pattern: '/roles',
    tokens: [{"old":"/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles']['types'],
  },
  'roles.update': {
    methods: ["PATCH"],
    pattern: '/roles',
    tokens: [{"old":"/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.update']['types'],
  },
  'settings': {
    methods: ["GET","HEAD"],
    pattern: '/settings',
    tokens: [{"old":"/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings']['types'],
  },
  'settings.general': {
    methods: ["GET","HEAD"],
    pattern: '/settings/general',
    tokens: [{"old":"/settings/general","type":0,"val":"settings","end":""},{"old":"/settings/general","type":0,"val":"general","end":""}],
    types: placeholder as Registry['settings.general']['types'],
  },
  'settings.general.update': {
    methods: ["PATCH"],
    pattern: '/settings/general',
    tokens: [{"old":"/settings/general","type":0,"val":"settings","end":""},{"old":"/settings/general","type":0,"val":"general","end":""}],
    types: placeholder as Registry['settings.general.update']['types'],
  },
  'settings.smtp': {
    methods: ["GET","HEAD"],
    pattern: '/settings/smtp',
    tokens: [{"old":"/settings/smtp","type":0,"val":"settings","end":""},{"old":"/settings/smtp","type":0,"val":"smtp","end":""}],
    types: placeholder as Registry['settings.smtp']['types'],
  },
  'settings.smtp.update': {
    methods: ["PATCH"],
    pattern: '/settings/smtp',
    tokens: [{"old":"/settings/smtp","type":0,"val":"settings","end":""},{"old":"/settings/smtp","type":0,"val":"smtp","end":""}],
    types: placeholder as Registry['settings.smtp.update']['types'],
  },
  'settings.smtp.test': {
    methods: ["POST"],
    pattern: '/settings/smtp/test',
    tokens: [{"old":"/settings/smtp/test","type":0,"val":"settings","end":""},{"old":"/settings/smtp/test","type":0,"val":"smtp","end":""},{"old":"/settings/smtp/test","type":0,"val":"test","end":""}],
    types: placeholder as Registry['settings.smtp.test']['types'],
  },
  'settings.sms': {
    methods: ["GET","HEAD"],
    pattern: '/settings/sms',
    tokens: [{"old":"/settings/sms","type":0,"val":"settings","end":""},{"old":"/settings/sms","type":0,"val":"sms","end":""}],
    types: placeholder as Registry['settings.sms']['types'],
  },
  'settings.sms.update': {
    methods: ["PATCH"],
    pattern: '/settings/sms',
    tokens: [{"old":"/settings/sms","type":0,"val":"settings","end":""},{"old":"/settings/sms","type":0,"val":"sms","end":""}],
    types: placeholder as Registry['settings.sms.update']['types'],
  },
  'settings.whatsapp': {
    methods: ["GET","HEAD"],
    pattern: '/settings/whatsapp',
    tokens: [{"old":"/settings/whatsapp","type":0,"val":"settings","end":""},{"old":"/settings/whatsapp","type":0,"val":"whatsapp","end":""}],
    types: placeholder as Registry['settings.whatsapp']['types'],
  },
  'settings.whatsapp.update': {
    methods: ["PATCH"],
    pattern: '/settings/whatsapp',
    tokens: [{"old":"/settings/whatsapp","type":0,"val":"settings","end":""},{"old":"/settings/whatsapp","type":0,"val":"whatsapp","end":""}],
    types: placeholder as Registry['settings.whatsapp.update']['types'],
  },
  'settings.other': {
    methods: ["GET","HEAD"],
    pattern: '/settings/other',
    tokens: [{"old":"/settings/other","type":0,"val":"settings","end":""},{"old":"/settings/other","type":0,"val":"other","end":""}],
    types: placeholder as Registry['settings.other']['types'],
  },
  'settings.other.update': {
    methods: ["PATCH"],
    pattern: '/settings/other',
    tokens: [{"old":"/settings/other","type":0,"val":"settings","end":""},{"old":"/settings/other","type":0,"val":"other","end":""}],
    types: placeholder as Registry['settings.other.update']['types'],
  },
  'settings.security': {
    methods: ["GET","HEAD"],
    pattern: '/settings/security',
    tokens: [{"old":"/settings/security","type":0,"val":"settings","end":""},{"old":"/settings/security","type":0,"val":"security","end":""}],
    types: placeholder as Registry['settings.security']['types'],
  },
  'settings.security.update': {
    methods: ["PATCH"],
    pattern: '/settings/security',
    tokens: [{"old":"/settings/security","type":0,"val":"settings","end":""},{"old":"/settings/security","type":0,"val":"security","end":""}],
    types: placeholder as Registry['settings.security.update']['types'],
  },
  'settings.security.mfa.start': {
    methods: ["POST"],
    pattern: '/settings/security/mfa/start',
    tokens: [{"old":"/settings/security/mfa/start","type":0,"val":"settings","end":""},{"old":"/settings/security/mfa/start","type":0,"val":"security","end":""},{"old":"/settings/security/mfa/start","type":0,"val":"mfa","end":""},{"old":"/settings/security/mfa/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['settings.security.mfa.start']['types'],
  },
  'settings.security.mfa.confirm': {
    methods: ["POST"],
    pattern: '/settings/security/mfa/confirm',
    tokens: [{"old":"/settings/security/mfa/confirm","type":0,"val":"settings","end":""},{"old":"/settings/security/mfa/confirm","type":0,"val":"security","end":""},{"old":"/settings/security/mfa/confirm","type":0,"val":"mfa","end":""},{"old":"/settings/security/mfa/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['settings.security.mfa.confirm']['types'],
  },
  'settings.security.mfa.disable': {
    methods: ["POST"],
    pattern: '/settings/security/mfa/disable',
    tokens: [{"old":"/settings/security/mfa/disable","type":0,"val":"settings","end":""},{"old":"/settings/security/mfa/disable","type":0,"val":"security","end":""},{"old":"/settings/security/mfa/disable","type":0,"val":"mfa","end":""},{"old":"/settings/security/mfa/disable","type":0,"val":"disable","end":""}],
    types: placeholder as Registry['settings.security.mfa.disable']['types'],
  },
  'settings.quickbooks': {
    methods: ["GET","HEAD"],
    pattern: '/settings/quickbooks',
    tokens: [{"old":"/settings/quickbooks","type":0,"val":"settings","end":""},{"old":"/settings/quickbooks","type":0,"val":"quickbooks","end":""}],
    types: placeholder as Registry['settings.quickbooks']['types'],
  },
  'settings.quickbooks.connect': {
    methods: ["GET","HEAD"],
    pattern: '/settings/quickbooks/connect',
    tokens: [{"old":"/settings/quickbooks/connect","type":0,"val":"settings","end":""},{"old":"/settings/quickbooks/connect","type":0,"val":"quickbooks","end":""},{"old":"/settings/quickbooks/connect","type":0,"val":"connect","end":""}],
    types: placeholder as Registry['settings.quickbooks.connect']['types'],
  },
  'settings.quickbooks.disconnect': {
    methods: ["POST"],
    pattern: '/settings/quickbooks/disconnect',
    tokens: [{"old":"/settings/quickbooks/disconnect","type":0,"val":"settings","end":""},{"old":"/settings/quickbooks/disconnect","type":0,"val":"quickbooks","end":""},{"old":"/settings/quickbooks/disconnect","type":0,"val":"disconnect","end":""}],
    types: placeholder as Registry['settings.quickbooks.disconnect']['types'],
  },
  'settings.quickbooks.credentials': {
    methods: ["PATCH"],
    pattern: '/settings/quickbooks/credentials',
    tokens: [{"old":"/settings/quickbooks/credentials","type":0,"val":"settings","end":""},{"old":"/settings/quickbooks/credentials","type":0,"val":"quickbooks","end":""},{"old":"/settings/quickbooks/credentials","type":0,"val":"credentials","end":""}],
    types: placeholder as Registry['settings.quickbooks.credentials']['types'],
  },
  'settings.quickbooks.test': {
    methods: ["POST"],
    pattern: '/settings/quickbooks/test',
    tokens: [{"old":"/settings/quickbooks/test","type":0,"val":"settings","end":""},{"old":"/settings/quickbooks/test","type":0,"val":"quickbooks","end":""},{"old":"/settings/quickbooks/test","type":0,"val":"test","end":""}],
    types: placeholder as Registry['settings.quickbooks.test']['types'],
  },
  'settings.quickbooks.update': {
    methods: ["PATCH"],
    pattern: '/settings/quickbooks',
    tokens: [{"old":"/settings/quickbooks","type":0,"val":"settings","end":""},{"old":"/settings/quickbooks","type":0,"val":"quickbooks","end":""}],
    types: placeholder as Registry['settings.quickbooks.update']['types'],
  },
  'invoices.quickbooks.retry': {
    methods: ["POST"],
    pattern: '/invoices/:id/quickbooks/retry',
    tokens: [{"old":"/invoices/:id/quickbooks/retry","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/quickbooks/retry","type":1,"val":"id","end":""},{"old":"/invoices/:id/quickbooks/retry","type":0,"val":"quickbooks","end":""},{"old":"/invoices/:id/quickbooks/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['invoices.quickbooks.retry']['types'],
  },
  'customers.quickbooks.retry': {
    methods: ["POST"],
    pattern: '/customers/:id/quickbooks/retry',
    tokens: [{"old":"/customers/:id/quickbooks/retry","type":0,"val":"customers","end":""},{"old":"/customers/:id/quickbooks/retry","type":1,"val":"id","end":""},{"old":"/customers/:id/quickbooks/retry","type":0,"val":"quickbooks","end":""},{"old":"/customers/:id/quickbooks/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['customers.quickbooks.retry']['types'],
  },
  'profile': {
    methods: ["GET","HEAD"],
    pattern: '/profile',
    tokens: [{"old":"/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile']['types'],
  },
  'user_settings': {
    methods: ["GET","HEAD"],
    pattern: '/user-settings',
    tokens: [{"old":"/user-settings","type":0,"val":"user-settings","end":""}],
    types: placeholder as Registry['user_settings']['types'],
  },
  'user_settings.password': {
    methods: ["PATCH"],
    pattern: '/user-settings/password',
    tokens: [{"old":"/user-settings/password","type":0,"val":"user-settings","end":""},{"old":"/user-settings/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['user_settings.password']['types'],
  },
  'session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['session.destroy']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
